name: eut_app
description: A new Flutter project.



publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  local_auth: ^2.0.0
  sidebarx: ^0.2.1+1
  google_fonts: ^2.3.2 
  flutter_screenutil: ^5.5.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:


  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/eut.jpg
    - assets/images/national.png
    - assets/images/food5.jpeg
    - assets/images/food.png
    - assets/icons/profileicon.png

  uses-material-design: true
